### ISSUE TITLE
请求接入zipkin

### ISSUE THREAD

**Issue by AtrisMio** [dubbo/js-for-apache-dubbo#86]
您有计划接入zipkin么？

我最近写了个zipkin的接入
https://github.com/AtrisMio/node-dubbo-sleuth

如果可以的话，希望能参考下您的接入方案

**Comment by creasy2010** [comment]
我们内部有一个. 我看下发出来呢.

**Comment by AtrisMio** [comment]
@creasy2010 
好哒    感谢
