### ISSUE TITLE
consumer 注册信息跟原生dubbo consumer不一致

### ISSUE THREAD

**Issue by sunchuanleihit** [dubbo/js-for-apache-dubbo#95]
dubbo2.js 启动consumer的时候会往zk上注册url
consumer://172.16.48.199/com.arch.tail.demo_provider.DemoProvider?ip=172.16.48.199&port=57058&interface=com.arch.tail.demo_provider.DemoProvider&application=node-egg-bff&category=consumers&dubbo=2.2.0.3&method=&revision=&version=1.0.0&group=&side=consumer&check=false

这里面比原生consumer多了ip port这个是出于什么考虑。

![image](https://user-images.githubusercontent.com/5242501/56740199-0dc73500-67a3-11e9-932a-4ed3beb7bf51.png)
这里的consumer数量会不会太多？

假如demoProvider有十台机器， consumer有十台， 那么按这个逻辑
/dubbo/com.arch.tail.demo_provider.DemoProvider/consumers 下就会新增100个子节点
原生的dubbo只会新增10个

![image](https://user-images.githubusercontent.com/5242501/56740947-824ea380-67a4-11e9-8aea-1c88a9d2bfc9.png)

ICreateConsumerParam 里把 host port dubboVersion去掉的话会不会有什么影响

**Comment by hufeng** [comment]
@sunchuanleihit 我来看下文档，印象是有ip和port的，这样精确知道消费了那个provider

**Comment by hufeng** [comment]
@sunchuanleihit 哈哈，是没有 3ks， 我来把这块整理下 

参考一个标准的，

![image](https://user-images.githubusercontent.com/533008/56857614-74ff0800-69a2-11e9-9ac8-1e9e22abe3e3.png)

**Comment by hufeng** [comment]
@sunchuanleihit 我来merge下你的pr 然后再规范下我们的consumer的参数 感谢pr

**Comment by sunchuanleihit** [comment]
> @sunchuanleihit 我来merge下你的pr 然后再规范下我们的consumer的参数 感谢pr

好的，感谢

**Comment by hufeng** [comment]
@sunchuanleihit relase [dubbo2.js@2.3.9](https://github.com/dubbo/js-for-apache-dubbo/releases/tag/dubbo2.js%402.3.9)
