### ISSUE TITLE
泛型支持问题

### ISSUE THREAD

**Issue by sunchuanleihit** [dubbo/js-for-apache-dubbo#98]
这是我定义的Provider接口

![image](https://user-images.githubusercontent.com/5242501/56849527-2745b980-6928-11e9-8d87-0ebb5c15e23f.png)

下面是Response定义
![image](https://user-images.githubusercontent.com/5242501/56849537-3e84a700-6928-11e9-8d04-d21e0e030cb3.png)
![image](https://user-images.githubusercontent.com/5242501/56849542-4b08ff80-6928-11e9-93bc-28ec12766cdd.png)

下面是我的实现
![image](https://user-images.githubusercontent.com/5242501/56849588-fade6d00-6928-11e9-806a-59a24399b33f.png)

执行getUserInfo的时候泛型没问题
![image](https://user-images.githubusercontent.com/5242501/56849607-3e38db80-6929-11e9-8438-236373237add.png)
返回内容如下
{ res:
   { t: { email: 'csun.asd', name: null, id: 23 },
     info: { name: 'test', id: '1' },
     status: 'ok' },
  err: null }

但是在我执行下面getList的时候会有问题。
  let b = await dubbo.service.DemoProvider.getList();
  console.log(b);

打印的内容如下

{ res: [ { t: [Object], info: null, status: 'ok' } ],
  err: null }
无法解析泛型，这个要怎么处理。

**Comment by hufeng** [comment]
@creasy2010 review 下
