### ISSUE TITLE
中间件低版本写法

### ISSUE THREAD

**Issue by wu666lei** [dubbo/js-for-apache-dubbo#99]
你好，请问对于低版本node不支持async的.不能用generator写法吗,这么写的话不提示报错不执行中间件也不正常返回接口结果呢，请教下不用async写法可以使用中间件吗:
dubbo.use(function*(ctx, next) {
        const startTime = Date.now();
        yield next;
        const endTime = Date.now();
        console.log('invoke cost time->', endTime - startTime);
      });

**Comment by hufeng** [comment]
hi @wu666lei ,不支持generator的写法，可以直接用promise的写法来写
因为底层依赖就是koa-compose，和koa的middleware的写法保持一致

```javascript
dubbo.use(function loseTime(ctx, next) {
  const startTime = Date.now();
  return next.then(() => {
     const endTime = Date.now();
     console.log('invoke cost time:', endTime - startTime);
  })
});

```

可以参考koa的middleware机制，
<img width="952" alt="image" src="https://user-images.githubusercontent.com/533008/56882348-ea97d080-6a95-11e9-90ae-e990f030b804.png">


希望可以解决你的问题
